---
title: "Homework04"
author: "Alyssa Neuhaus"
date: "2/5/2020"
output: html_document
---

1. Assign each expression to the value of the variable z and print the value stored in z

```{r}
x <- 1.1
a <- 2.2
b <- 3.3
```

```{r}
z <- x^{a^{b}}
print(z)
```

```{r}
z <- (x^{a})^{b}
print(z)
```

```{r}
z <- 3*x^{3} + 2*x^{2} + 1
print(z)
```

2. Using the rep and seq functions, create vectors

```{r}
x <-seq(1, 8)
y <-seq(7,1)
c(x,y)
```
```{r}
rep(c(1, 2, 3, 4, 5), c(1, 2, 3, 4, 5))
```

```{r}
rep(c(5, 4, 3, 2, 1), c(1, 2, 3, 4, 5))
```

3. Create a vector of two random uniform numbers and convert into polar coordinates

```{r}
x <-runif(1)
y <-runif(1)
c(x,y)
r <-((x^{2})+(y^{2}))^{1/2}
a <-atan(y/x)
c(r,a)
```

4. Update queue successively 

```{r}
queue <- c("sheep", "fox", "owl", "ant")
a <- c("serpent") # serpent arrives
c(queue, a)
c(queue[2:4], a) # sheep enters ark
d <- c("donkey")
c(d, queue, a) # donkey talks his way to front of line
c(d, queue) #serpent leaves
c(d, queue[2], queue[4]) #owl leaves
f <- c("aphid")
c(d, queue[2], f, queue [4]) # aphid cuts in front of ant
```

5. Create a vector of all the integers from 1 to 100 that are not divisible by 2, 3, or 7

```{r}
z <- 1:100
z [rowSums(outer(z, c(2, 3, 7), "%%") == 0) == 0] # rowSums identifies numbers from 1-100 that are not perfectly divided by 2, 3, or 7. == is there to make sure the vectors are exactly the same length. %% gives the remainder of the first vector with the second
```




